//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace File.Cutter {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class FileData : global::System.Configuration.ApplicationSettingsBase {
        
        private static FileData defaultInstance = ((FileData)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FileData())));
        
        public static FileData Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\projects\\tragisj\\gearmaiden\\lists\\gearlist.csv")]
        public string Gear {
            get {
                return ((string)(this["Gear"]));
            }
            set {
                this["Gear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\projects\\tragisj\\gearmaiden\\lists\\gearlegend.csv")]
        public string Legend {
            get {
                return ((string)(this["Legend"]));
            }
            set {
                this["Legend"] = value;
            }
        }
    }
}
